version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app 
    environment:
      - FLASK_APP=main_score.py 
      - FLASK_RUN_HOST=0.0.0.0 # for checking outside the container
    restart: always 
